# Generated by Django 2.2.2 on 2019-06-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190627_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='explain',
            field=models.TextField(blank=True),
        ),
    ]
