# Generated by Django 2.2.2 on 2019-06-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
