# Generated by Django 2.2.2 on 2019-07-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
