# Generated by Django 2.2.4 on 2019-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190826_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.FloatField(default=0.0),
        ),
    ]
