# Generated by Django 2.2.2 on 2019-07-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190627_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='haveAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
